### ISSUE TITLE
window.location.hash and setHistory error

### ISSUE THREAD

**Issue by dmathieu** [smparkes/env-js#7]
Hello,

I'm using envjs (with Harmony). But when I define, in my javascript, `window.location.hash`, I get the following error from envjs :

```
1)
Johnson::Error in 'MainController should load the record's content'
setHistory is not defined
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/env.js:1900 [JavaScript]
```

**Comment by dmathieu** [comment]
Actually it seems to be on every `window.location` object.
When doing a `window.location.href = xxx`, I get the following error :

```
2)
Johnson::Error in 'MainController should generate a csv'
$events[target.uuid] is undefined
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/env.js:2176:in `__dispatchEvent__' [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:1718 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:7051 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:7076 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:6775 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:6815 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:7108 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:7047 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:7076 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:6786 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:6815 [JavaScript]
```

That didn't happen previously. The only thing I did was to update env-js to it's last version (and so, as the dependencies requested it, update johnson to it's last prerelease).

**Comment by smparkes** [comment]
Hmmm ... I'll look at it. I could probably figure it out, but do you have a simple harmony script that shows this?

**Comment by smparkes** [comment]
Do you have onload event handlers? There are a lot of events to cover and we've been doing it more or less on an as-needed basis. It looks like you've hit one of the corner cases. I just need a little help figuring out which one ...

**Comment by dmathieu** [comment]
I don't have the code right here (it's at work. It's home time on time zone (France)).
There's a lot of onload event handlers.
But they're all defined with jquery as `jQuery(document).ready()`.

**Comment by smparkes** [comment]
Sorry, I meant _onunload_.

**Comment by dmathieu** [comment]
No, there's no onunload.

**Comment by smparkes** [comment]
Okay. I know where in the code this is happening, but not sure exactly why at this point. There could be a few reasons. It's kinda tricky code.

Is it the kind of thing you could post at least part of the code for?

**Comment by dmathieu** [comment]
Well there's quite a lot of code in the application and it could be anywhere ;)
From what I've seen, it happens to be when we call `window.location.*`

**Comment by smparkes** [comment]
Yeah, I figured there was a fair amount of code.

It's related to firing an event. There's an element that has an event listener identified with it, but there's another data structure that should have a record of that, and it'd doesn't, which is why you're getting the undefined error.

What I'm not sure about is the sequence of events that is causing this  to be the case.

It wouldn't be too hard to track down with a repeatable test case. Without it ...

**Comment by dmathieu** [comment]
Maybe you could try to explain it so I could try to track it down.

**Comment by smparkes** [comment]
I don't actually know that part of the code all that well. I've done some work around it, but not on the particular array.

It looks like it's putting an object in an array when you add a listener to an event (look at the line numbers in the traceback). The "uuid" is just an index into an array. But then when it tries to deliver an event, it doesn't find anything in that array at that location.

I'm kinda wondering if it's trying to deliver an event to an old window ... not sure we've looked at that case (multiwindow support is relatively new).

All I would do is go in there and start enabling/inserting debug statements ...

I think this code has been changed a fair amount in the curent env.js trunk.

I hope to work on integrating that, but it won't happen for a few weeks, at least.

**Comment by dmathieu** [comment]
No, there's only one window.
I'll do some tests and come back here if I find something.

**Comment by smparkes** [comment]
Every time you set window.location, you're getting a new window. That's the way browsers work. The reference called "window" points at the newest one, but there are old ones around, until they get gc'd.

But I still can't come up with firm scenario that would cause what you're seeing. Let me know what you find.

**Comment by dmathieu** [comment]
I can actually reproduce it quite easily, without any context.
With the following : http://gist.github.com/348854

When I launch the test.rb file, I get the following error :

```
/usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/env.js:1900 [JavaScript]: setHistory is not defined (Johnson::Error)
    from inline:1 [JavaScript]
    from inline:1 [JavaScript]
    from /usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:4708 [JavaScript]
    from /usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/static.js:4589 [JavaScript]
    from inline:1 [JavaScript]
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in `evaluate_compiled_script'
    from /usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/runtime.rb:54:in `evaluate'
    from /usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/runtime.rb:318:in `extended'
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `call'
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `__send__'
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `send_with_possible_block'
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/ruby_land_proxy.rb:110:in `call_function_property'
    from /usr/lib64/ruby/gems/1.8/gems/envjs-0.2.0/lib/envjs/env.js:110 [JavaScript]
    from /usr/lib64/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/ruby_land_proxy.rb:110:in `method_missing'
    from /usr/lib64/ruby/gems/1.8/gems/harmony-0.5.4/lib/harmony/page.rb:90:in `execute_js'
    from test.rb:5
```

I have the following installed :
- johnson 2.0.0.pre3
- envjs 0.2.0
- harmony 0.5.4

**Comment by smparkes** [comment]
Yeah. There are two perhaps related issues here. I''ve been looking more at the second. The first should be a quick fix. I'll look at in the morning and see where it gets us.

**Comment by smparkes** [comment]
envjs 0.3.1 will fix the missing fn on setting the hash. Not sure if it will have any impact on the event problem ...

**Comment by dmathieu** [comment]
You mean 0.2.1 don't you ? ;)

**Comment by smparkes** [comment]
Don't think so. 0.3.1 is pushed. I did a 0.3.0 at some point with a bunch of little stuff.  Not sure if/when I pushed that to gemcutter. Yesterday, maybe? It had more than just bug fixes, so it was 0.3.0 rather than 0.2.1.

**Comment by dmathieu** [comment]
You missed the git tag then ;)

**Comment by smparkes** [comment]
Ah. Right. I had my remotes setup weird so hoe wasn't pushing the tags and I forgot to do it manually. Fixed that. Thanks.

**Comment by smparkes** [comment]
Did you get a chance to check the uuid issue with the 0.3.1?

**Comment by dmathieu** [comment]
I've just checked it. It doesn't change anything.

```
Johnson::Error in 'MainController should send the pdf'
$events[target.uuid] is undefined
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/env.js:2177:in `__dispatchEvent__' [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:1718 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:7051 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:7076 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:6775 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:6815 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:7108 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:7047 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:7076 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:6786 [JavaScript]
/usr/lib64/ruby/gems/1.8/gems/envjs-0.3.1/lib/envjs/static.js:6815 [JavaScript]
```

**Comment by smparkes** [comment]
Yeah, I didn't think it would.

This is going to be hard to diagnose without a test case. It wouldn't be that hard if I could run it. I would think it's a fairly simple matter of watching where the events get a uuid set and when they get added/removed from the $events array. But without a test, it's pretty hard. I didn't write this code and it's test coverage is too great (though that's improving all the time ...)

**Comment by dmathieu** [comment]
I've taken a look and could write a test for it which fails.
http://github.com/dmathieu/env-js/commit/b4d4f85e4694241919161d229d94aff476f1c75e

**Comment by smparkes** [comment]
There are a few things going on in this issue. I don't think the hash issue is the same as the uuid issue, but I'm happy to fix it.

There was an issue with setting the hash, though I don't think  it's what your test was hitting. The test was slightly wrong (using Chrome as a reference): the hash accessor returns the string with the #. Tweaked the test and it runs.

I'm still don't think this is the uuid issue, though. But, hey, I've been wrong lots of other times and since I don't know what the issue is ...

**Comment by smparkes** [comment]
By the way, I pushed 0.3.4 with tweaked tests.

**Comment by smparkes** [comment]
Just pushed 0.3.5. Still an issue?

**Comment by gentooboontoo** [comment]
Yes, undefined $events[target.uuid] is still an issue with 0.3.8. I'm working on the same code as dmathieu at the time.

But I have managed to make a small test reproducing it:
https://gist.github.com/818478

You need to have jquery.js (not the origin of the failure) and any binary file named random.bin.

In short, we are triggering a download with a select element then reinitialize select element to default choice (the reinitialization triggers the failure).
We use a form element to make a POST request with many parameters (not possible to download via xhr).

I suppose that the failure is due to the fact that envjs doesn't handle "pseudo-download" and replace current DOM with downloaded file. Is this right?

Could it be easily solved or is there any workaround?

PS:
- It also warns about "malformed UTF-8 character" because it tries to decode binary file as utf-8 string (whereas content-type is application/octet-stream).
- In envjsrb with this test, I have to issue **twice** "window.location = "http://0.0.0.0:8080/tmp/envjs-failtest/main.html" to load embedded scripts without errors whereas window.open("http://0.0.0.0:8080/tmp/envjs-failtest/main.html") works perfectly. Should window.location not be directly used to load URLs?

Thanks.

Julien

**Comment by smparkes** [comment]
I don't have a good answer. Binary data doesn't work consistently right now because anything that goes through spidermonkey (which is most things) goes into a string and strings have to be UTF.

A patch would be great, but I'm not going to have time to look into this more myself anytime too soon.

You could look at the main envjs branch but I don't really know much about it's ruby and/or multiple window support.
